/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.generadorConstancia.ui;

import com.docenteModel.DocenteModel;
import com.services.DocenteServices;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author adria
 */
public class DatosEvaluadores extends javax.swing.JPanel {

    /**
     * Creates new form DatosEvaluadores
     */
    List<DocenteModel> evaluadores;
    

    public DatosEvaluadores() {
        initComponents();
        getEvaluadores();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        gradoEvaluador1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cedulaEvaluador1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gradoEvaluador2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cedulaEvaluador2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        gradoEvaluador3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cedulaEvaluador3 = new javax.swing.JTextField();
        comboNombreEvaluador1 = new javax.swing.JComboBox<>();
        comboNombreEvaluador2 = new javax.swing.JComboBox<>();
        comboNombreEvaluador3 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(750, 400));
        setMinimumSize(new java.awt.Dimension(750, 400));
        setPreferredSize(new java.awt.Dimension(750, 400));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Datos de Evaluadores");

        jScrollPane1.setBorder(null);
        jScrollPane1.setColumnHeaderView(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(730, 300));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(730, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(730, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(740, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(740, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 600));

        gradoEvaluador1.setEnabled(false);
        gradoEvaluador1.setMaximumSize(new java.awt.Dimension(300, 25));
        gradoEvaluador1.setMinimumSize(new java.awt.Dimension(300, 25));
        gradoEvaluador1.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Grado");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Presidente");

        cedulaEvaluador1.setEnabled(false);
        cedulaEvaluador1.setMaximumSize(new java.awt.Dimension(200, 25));
        cedulaEvaluador1.setMinimumSize(new java.awt.Dimension(200, 25));
        cedulaEvaluador1.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Secretario");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Grado");

        gradoEvaluador2.setEnabled(false);
        gradoEvaluador2.setMaximumSize(new java.awt.Dimension(300, 25));
        gradoEvaluador2.setMinimumSize(new java.awt.Dimension(300, 25));
        gradoEvaluador2.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Cédula");

        cedulaEvaluador2.setEnabled(false);
        cedulaEvaluador2.setMaximumSize(new java.awt.Dimension(200, 25));
        cedulaEvaluador2.setMinimumSize(new java.awt.Dimension(200, 25));
        cedulaEvaluador2.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Cédula");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Vocal");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Nombre");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Grado");

        gradoEvaluador3.setEnabled(false);
        gradoEvaluador3.setMaximumSize(new java.awt.Dimension(300, 25));
        gradoEvaluador3.setMinimumSize(new java.awt.Dimension(300, 25));
        gradoEvaluador3.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Cédula");

        cedulaEvaluador3.setEnabled(false);
        cedulaEvaluador3.setMaximumSize(new java.awt.Dimension(200, 25));
        cedulaEvaluador3.setMinimumSize(new java.awt.Dimension(200, 25));
        cedulaEvaluador3.setPreferredSize(new java.awt.Dimension(200, 25));

        comboNombreEvaluador1.setToolTipText("Evaluador");
        comboNombreEvaluador1.setMaximumSize(new java.awt.Dimension(300, 25));
        comboNombreEvaluador1.setMinimumSize(new java.awt.Dimension(300, 25));
        comboNombreEvaluador1.setPreferredSize(new java.awt.Dimension(300, 25));
        comboNombreEvaluador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNombreEvaluador1ActionPerformed(evt);
            }
        });

        comboNombreEvaluador2.setToolTipText("Evaluador");
        comboNombreEvaluador2.setMaximumSize(new java.awt.Dimension(300, 25));
        comboNombreEvaluador2.setMinimumSize(new java.awt.Dimension(300, 25));
        comboNombreEvaluador2.setPreferredSize(new java.awt.Dimension(300, 25));
        comboNombreEvaluador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNombreEvaluador2ActionPerformed(evt);
            }
        });

        comboNombreEvaluador3.setToolTipText("Evaluador");
        comboNombreEvaluador3.setMaximumSize(new java.awt.Dimension(300, 25));
        comboNombreEvaluador3.setMinimumSize(new java.awt.Dimension(300, 25));
        comboNombreEvaluador3.setPreferredSize(new java.awt.Dimension(300, 25));
        comboNombreEvaluador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNombreEvaluador3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(gradoEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(gradoEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboNombreEvaluador3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboNombreEvaluador2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(153, 153, 153)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cedulaEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cedulaEvaluador3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(gradoEvaluador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(comboNombreEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cedulaEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNombreEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradoEvaluador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNombreEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradoEvaluador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaEvaluador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNombreEvaluador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradoEvaluador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPane1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void getEvaluadores(){
        
        DocenteServices es = new DocenteServices();
        evaluadores = es.getEvaluadores();
        
        if(evaluadores.isEmpty()){
            JOptionPane.showMessageDialog(this,"Hubo un problema al cargar los datos");
            
        }else{
            evaluadores.forEach((DocenteModel dm) ->{
                comboNombreEvaluador1.addItem(dm.getNombre());
                comboNombreEvaluador2.addItem(dm.getNombre());
                comboNombreEvaluador3.addItem(dm.getNombre());
            });
        }
        
    }
    
    
    private void comboNombreEvaluador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNombreEvaluador1ActionPerformed

        showEvaluadorData(comboNombreEvaluador1.getSelectedIndex(), cedulaEvaluador1, gradoEvaluador1);
    }//GEN-LAST:event_comboNombreEvaluador1ActionPerformed

    private void comboNombreEvaluador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNombreEvaluador2ActionPerformed
        
        showEvaluadorData(comboNombreEvaluador2.getSelectedIndex(), cedulaEvaluador2, gradoEvaluador2);

    }//GEN-LAST:event_comboNombreEvaluador2ActionPerformed

    private void comboNombreEvaluador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNombreEvaluador3ActionPerformed
        
        showEvaluadorData(comboNombreEvaluador3.getSelectedIndex(), cedulaEvaluador3, gradoEvaluador3);

    }//GEN-LAST:event_comboNombreEvaluador3ActionPerformed

    private void showEvaluadorData(int index, JTextField cedula, JTextField grado){
         
        DocenteModel dm = evaluadores.get(index);
        cedula.setText(dm.getCedula());
        grado.setText(dm.getGrado());
        
       
    }
    
    public List<DocenteModel> evaluadoresList(){
        
        List<DocenteModel> temp = new ArrayList<>();
        List<JComboBox> combos = new ArrayList<>();
        
        combos.add(comboNombreEvaluador1);
        combos.add(comboNombreEvaluador2);
        combos.add(comboNombreEvaluador3);
        
        combos.forEach((JComboBox combo) ->{
        
            DocenteModel dm = evaluadores.get(combo.getSelectedIndex());
            temp.add(dm);
        
        });
        
        return temp;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulaEvaluador1;
    private javax.swing.JTextField cedulaEvaluador2;
    private javax.swing.JTextField cedulaEvaluador3;
    private javax.swing.JComboBox<String> comboNombreEvaluador1;
    private javax.swing.JComboBox<String> comboNombreEvaluador2;
    private javax.swing.JComboBox<String> comboNombreEvaluador3;
    private javax.swing.JTextField gradoEvaluador1;
    private javax.swing.JTextField gradoEvaluador2;
    private javax.swing.JTextField gradoEvaluador3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
