/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.generadorConstancia.ui;

import com.constanciaModel.ConstanciaModel;
import com.constanciaModel.dateGenerator.DateGenerator;
import com.docenteModel.DocenteModel;
import com.alumnoModel.AlumnoModel;
import com.generadorConstancia.GeneradorConstancia;
import com.proyectoModel.ProyectoModel;
import com.services.ConstanciaServices;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import jdk.jshell.EvalException;

/**
 *
 * @author adria
 */
public class TesisScreen extends javax.swing.JPanel {

    /**
     * Creates new form DatosScreen
     */
    DatosAlumnoScreen alumnoDatos = new DatosAlumnoScreen();
    FechaTesisScreen fechaTesisDatos = new FechaTesisScreen();
    DatosEvaluadores evaluadoresDatos = new DatosEvaluadores();

    public TesisScreen() {
        initComponents();

        alumnoDatos.setSize(740, 400);
        alumnoDatos.setLocation(0, 0);

        datosPanel.removeAll();
        datosPanel.add(alumnoDatos);
        datosPanel.revalidate();
        datosPanel.repaint();

        anteriorButton.setVisible(false);
        finalizarButton.setVisible(false);

        guardarButton.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datosPanel = new javax.swing.JPanel();
        siguienteButton = new javax.swing.JButton();
        anteriorButton = new javax.swing.JButton();
        finalizarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 102));
        setMaximumSize(new java.awt.Dimension(780, 577));
        setMinimumSize(new java.awt.Dimension(780, 577));
        setPreferredSize(new java.awt.Dimension(780, 577));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(740, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(740, 500));
        jPanel1.setName(""); // NOI18N

        datosPanel.setBackground(new java.awt.Color(204, 204, 204));
        datosPanel.setMaximumSize(new java.awt.Dimension(740, 400));
        datosPanel.setMinimumSize(new java.awt.Dimension(740, 400));
        datosPanel.setName(""); // NOI18N
        datosPanel.setPreferredSize(new java.awt.Dimension(740, 400));

        javax.swing.GroupLayout datosPanelLayout = new javax.swing.GroupLayout(datosPanel);
        datosPanel.setLayout(datosPanelLayout);
        datosPanelLayout.setHorizontalGroup(
            datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        datosPanelLayout.setVerticalGroup(
            datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        siguienteButton.setBackground(new java.awt.Color(0, 51, 102));
        siguienteButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        siguienteButton.setForeground(new java.awt.Color(255, 255, 255));
        siguienteButton.setText("Siguiente");
        siguienteButton.setBorder(null);
        siguienteButton.setBorderPainted(false);
        siguienteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguienteButton.setMargin(new java.awt.Insets(22, 50, 22, 50));
        siguienteButton.setMaximumSize(new java.awt.Dimension(100, 35));
        siguienteButton.setMinimumSize(new java.awt.Dimension(100, 35));
        siguienteButton.setPreferredSize(new java.awt.Dimension(100, 35));
        siguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteButtonActionPerformed(evt);
            }
        });

        anteriorButton.setBackground(new java.awt.Color(204, 204, 204));
        anteriorButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        anteriorButton.setForeground(new java.awt.Color(0, 51, 102));
        anteriorButton.setText("Anterior");
        anteriorButton.setBorder(null);
        anteriorButton.setBorderPainted(false);
        anteriorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anteriorButton.setMargin(new java.awt.Insets(22, 50, 22, 50));
        anteriorButton.setMaximumSize(new java.awt.Dimension(100, 35));
        anteriorButton.setMinimumSize(new java.awt.Dimension(100, 35));
        anteriorButton.setPreferredSize(new java.awt.Dimension(100, 35));
        anteriorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButtonActionPerformed(evt);
            }
        });

        finalizarButton.setBackground(new java.awt.Color(0, 51, 102));
        finalizarButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        finalizarButton.setForeground(new java.awt.Color(255, 255, 255));
        finalizarButton.setText("Finalizar");
        finalizarButton.setBorder(null);
        finalizarButton.setBorderPainted(false);
        finalizarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finalizarButton.setMargin(new java.awt.Insets(22, 50, 22, 50));
        finalizarButton.setMaximumSize(new java.awt.Dimension(100, 35));
        finalizarButton.setMinimumSize(new java.awt.Dimension(100, 35));
        finalizarButton.setPreferredSize(new java.awt.Dimension(100, 35));
        finalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarButtonActionPerformed(evt);
            }
        });

        guardarButton.setBackground(new java.awt.Color(0, 51, 102));
        guardarButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        guardarButton.setForeground(new java.awt.Color(255, 255, 255));
        guardarButton.setText("Guardar");
        guardarButton.setBorder(null);
        guardarButton.setBorderPainted(false);
        guardarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarButton.setMargin(new java.awt.Insets(22, 50, 22, 50));
        guardarButton.setMaximumSize(new java.awt.Dimension(100, 35));
        guardarButton.setMinimumSize(new java.awt.Dimension(100, 35));
        guardarButton.setPreferredSize(new java.awt.Dimension(100, 35));
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(anteriorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(siguienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(finalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(datosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anteriorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    int screenNum = 1;

    private void siguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteButtonActionPerformed
        screenNum++;
        changeScreen(screenNum);
    }//GEN-LAST:event_siguienteButtonActionPerformed

    private void anteriorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButtonActionPerformed
        screenNum--;
        changeScreen(screenNum);
    }//GEN-LAST:event_anteriorButtonActionPerformed

    private void finalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarButtonActionPerformed

        int resp = JOptionPane.showConfirmDialog(this.jPanel1, "¿Quieres continuar?", "Verifica tus datos", JOptionPane.OK_CANCEL_OPTION);

        if (resp == 0) {

            GeneradorConstancia gc = new GeneradorConstancia();
            ConstanciaModel cm = getDataConstancia();
            gc.generarConstanciaTitulacion(cm);

            System.out.println("Foja: " + cm.getFoja() + "\nFecha autorizacion: " + cm.getFechaAutorizacion() + "\nFecha expedicion: " + cm.getFechaExpedicion() + "\nFoja: " + cm.getFoja() + "\n");
            cm.getEvaluadoresList().forEach((DocenteModel dm) -> {

                System.out.println("ID: " + dm.getId() + "Nombre docente: " + dm.getNombre() + "Cedula: " + dm.getCedula() + "Grado: " + dm.getGrado() + "\n");
            });

            System.out.println("Nombre: " + cm.getAlumno().getNombre() + "\n Numero control: " + cm.getAlumno().getNumeroControl() + "\nCarrera: " + cm.getAlumno().getCarreraModel().getNombre()
                    + "\nTitulacion: " + cm.getProyecto().getMetodoTitulacion() + "\nProyecto: " + cm.getProyecto().getTemaProyecto() + "\n");
        }


    }//GEN-LAST:event_finalizarButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        int resp = JOptionPane.showConfirmDialog(this.jPanel1, "¿Quieres continuar?", "Verifica tus datos", JOptionPane.OK_CANCEL_OPTION);

        if (resp == 0) {
            ConstanciaServices as = new ConstanciaServices();

            if (as.isCreated(alumnoDatos.getNoControl())) {
                JOptionPane.showMessageDialog(datosPanel, "El alumno ya está registrado");
            } else {
                 Map<String, String> response = as.createConstancia(getDataConstancia());
                JOptionPane.showMessageDialog(datosPanel, response.get("mensaje"));
            }

        }
    }//GEN-LAST:event_guardarButtonActionPerformed

    private ConstanciaModel getDataConstancia() {

      
        AlumnoModel em = alumnoDatos.getEstudiante();
        ProyectoModel pm = alumnoDatos.getProyecto();

        List<DocenteModel> evaluadoresList = evaluadoresDatos.evaluadoresList();
        DateGenerator dg = new DateGenerator();

        String horaInicio = fechaTesisDatos.getHoraInicio();
        String horaTermino = fechaTesisDatos.getHoraTermino();
        String fechaExpedicion = dg.getFechaNormalLetra(fechaTesisDatos.getFechaExpedicion());
        String fechaAutorizacion = dg.getFechaNormalLetra(fechaTesisDatos.getFechaAutorizacion());
        String foja = fechaTesisDatos.getFoja();

        ConstanciaModel cm = new ConstanciaModel(em, evaluadoresList, pm, fechaAutorizacion, fechaExpedicion, foja,horaInicio, horaTermino);
        return cm;
    }

    public void changeScreen(int screenNum) {

        System.out.println(screenNum);

        switch (screenNum) {
            case 1:
                alumnoDatos.setSize(740, 455);
                alumnoDatos.setLocation(0, 0);

                datosPanel.removeAll();
                datosPanel.add(alumnoDatos);
                datosPanel.revalidate();
                datosPanel.repaint();

                anteriorButton.setVisible(false);

                break;

            case 2:
                fechaTesisDatos.setSize(780, 455);
                fechaTesisDatos.setLocation(0, 0);

                datosPanel.removeAll();
                datosPanel.add(fechaTesisDatos);
                datosPanel.revalidate();
                datosPanel.repaint();

                anteriorButton.setVisible(true);
                finalizarButton.setVisible(false);
                siguienteButton.setVisible(true);

                guardarButton.setVisible(false);

                break;

            case 3:
                evaluadoresDatos.setSize(780, 455);
                evaluadoresDatos.setLocation(0, 0);

                datosPanel.removeAll();
                datosPanel.add(evaluadoresDatos);
                datosPanel.revalidate();
                datosPanel.repaint();

                siguienteButton.setVisible(false);
                finalizarButton.setVisible(true);

                guardarButton.setVisible(true);
                break;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorButton;
    private javax.swing.JPanel datosPanel;
    private javax.swing.JButton finalizarButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton siguienteButton;
    // End of variables declaration//GEN-END:variables
}
